version: "3.1"

services:

  server:
    container_name: server
    build: 
      context: .
      dockerfile: ./src/dev.Dockerfile
    environment:
      - SECRETS=/app/options.json
    expose: 
      - "3001"
      - "8080"
    ports: 
      - "9229:9229"
    volumes:
      - ./dist:/app/dist
      - ./src/client/content:/app/dist/prod/content
      - ./package.json:/app/package.json
      - ./nodemon.json:/app/nodemon.json
      - ./src/server/secrets.json:/app/options.json
  
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - server
    volumes:
      - ./src/dev.nginx.conf:/etc/nginx/nginx.conf:ro
