version: "3.1"

services:

  server:
    container_name: server
    build: 
      context: .
      dockerfile: ./server/dev.Dockerfile
    ports:
      - "9229:9229"
    environment:
      - SECRETS=/server/options.json
    expose: 
      - "3001"
    volumes:
      - ./build:/server/build
      - ./package.json:/server/package.json
      - ./nodemon.json:/server/nodemon.json
      - ./server/secrets.json:/server/options.json
  
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - server
    volumes:
      - ./server/dev.nginx.conf:/etc/nginx/nginx.conf:ro
