version: "3.1"

services:

  app:
    container_name: app
    build: 
      context: .
      dockerfile: ./app/dev.Dockerfile
    ports:
      - "9229:9229"
    environment:
      - SECRETS=/app/options.json
    expose: 
      - "3001"
    volumes:
      - ./build:/app/build
      - ./package.json:/app/package.json
      - ./nodemon.json:/app/nodemon.json
      - ./app/secrets.json:/app/options.json
  
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./app/dev.nginx.conf:/etc/nginx/nginx.conf:ro
